services:
  billsplitter:
    environment:
      - PEOPLE=Felix,Nico,Sven,Markus
    build: .
    container_name: billsplitter_app
    ports:
      - "8501:8501"
    volumes:
      - ./db:/app/db
    restart: unless-stopped
