services:
  billsplitter:
    build: .
    container_name: billsplitter_app
    ports:
      - "8501:8501"
    environment:
      - PEOPLE=Felix,Nico,Sven,Markus
      - DB_DIR=/data
    volumes:
      - ./db:/data
    restart: unless-stopped